#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dynamicArray' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def dynamicArray(n, queries):
    # Write your code here
    lastNumber = 0
    seqList=[];
    for i in range(n):
        seqList.append([])
        #print(seqList,"Empty")
    res = [];
    for k, x, y in queries:
        index = (x^lastNumber)%n
        if k==1:
            seqList[index].append(y)
            #print(seqList,"Hey!")
        else:
            size = len(seqList[index])
            #print(seqList,"Hey2")
            #print(size,"Size")
            lastNumber = seqList[index][y%size]
            #print(lastNumber,"Lnumber")
            res.append(lastNumber)
            
    return res 
    #print(a, x, y, l)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    q = int(first_multiple_input[1])

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = dynamicArray(n, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
